site_name: semvertag
site_url: https://semvertag.modern-python.org
repo_url: https://github.com/modern-python/semvertag
docs_dir: docs
edit_uri: edit/main/docs/
nav:
  - Quick Start: index.md
  - Providers:
    - GitLab CI: providers/gitlab.md
    - GitHub Actions: providers/github.md
  - Strategies:
    - Branch prefix: strategies/branch-prefix.md
    - Conventional commits: strategies/conventional-commits.md

theme:
  name: material
  logo: assets/modern-python-white.svg
  favicon: assets/modern-python-mark.svg
  features:
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - header.autohide
    - announce.dismiss
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/git-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - css/brand.css

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/modern-python/semvertag
      name: GitHub
