import typing

from semvertag._types import Commit, Tag


class Provider(typing.Protocol):
    @property
    def name(self) -> str: ...

    def get_default_branch(self) -> str: ...
    def get_latest_commit_on_default_branch(self) -> Commit: ...
    def list_tags(self) -> list[Tag]: ...
    def create_tag(self, name: str, commit_sha: str) -> None: ...
